const fonts = {
    button: {
      fontFamily: 'Inter_18pt-SemiBold',
      fontSize: 15,
      color: '#ffff',
    },
    Text: {
      fontFamily: 'Inter_28pt-Regular',
      fontSize: 15,
      color: '#ffff',
    },
    Forgot: {
      fontFamily: 'Inter_28pt-Regular',
      fontSize: 15,
      color: '#ffff',
      textDecorationLine: 'underline',
      alignSelf: 'flex-end',
      paddingRight: 30,
      marginTop: 5,
      paddingBottom: 10,
    },
    Account: {
      fontFamily: 'Inter_28pt-Regular',
      fontSize: 15,
      color: '#5CFF6C',
    },
    Input: {
      fontFamily: 'Inter_28pt-Regular',
      height: 55,
      width: 350,
      padding: 10,
      borderColor: 'black',
      borderWidth: 2,
      backgroundColor: '#D9D9D9',
      borderRadius: 18,
      fontSize: 14, 
      color: '#4D5B4C',
      marginBottom: 8,
    },
    Back: {
      width: 50,
      height: 50,
      marginLeft: 10,
      marginTop: 10,
    },
    Sort: {
      width: 40,
      height: 40,
      marginLeft: 25,
      marginTop: -25,
    },
    Home: {
      fontFamily:  'ZillaSlab-Medium',
      fontSize: 35,
      color: 'white',
      textDecorationLine: 'underline',
    },
    Quotes: {
      fontFamily: 'ZillaSlab-Regular',
      fontSize: 26,
      color: 'white',
      lineHeight: 28,
      textAlign: 'center',
      backgroundColor: '#226C01',
      padding: 15,
      height: '58%',
      width: '95%',
      borderRadius: 20,
    },
    Description: {
      fontFamily: 'ZillaSlab-Regular',
      fontSize: 20,
      color: 'white',
      lineHeight: 28,
      textAlign: 'justify',
      padding: 15,
      height: '85%',
      width: '95%',
      borderRadius: 20,
    },
    Exercise: {
      fontFamily: 'Inter_28pt-Regular',
      fontSize: 20,
      color: 'white',
      textDecorationLine: 'underline',
    },
    Title: {
      fontFamily: 'Inter_28pt-Regular',
      fontSize: 12,
      color: '#FFFFFF',
      textAlign: 'center',
      marginTop: -15,
      paddingBottom: 10,
    },
    ExerciseDescription: {
      fontFamily: 'Inter_28pt-Regular',
      color: 'white',
      fontSize: 16,
      textAlign: 'justify',
      marginVertical: 20,
      lineHeight: 22,
    },
    ModalTitle: {
      fontFamily: 'Inter_24pt-Bold',
      fontSize: 24,
      color: 'white',
      marginVertical: 9,
      paddingLeft: 50,
      paddingRight: 50,
    },
    exerciseContainer: {
      marginBottom: 20,
      flexDirection: 'column',
    },
    ExerciseName: {
      fontSize: 26,
      marginBottom: 5,
      fontFamily: 'Inter_24pt-Bold',
      color: 'white',
      paddingTop: 30,
    },
    ExerciseStep: {
      fontSize: 16,
      marginLeft: 10,
      marginBottom: 5,
      fontFamily: 'Inter_28pt-Regular',
      color: 'white',
      textAlign: 'justify',
    },
    guide: {
      width: 350,
      height: 290,
    },
  };
  
  export default fonts;